# Set the location where you want to save the files generated by the script
#
# EXAMPLES
#
# Default relative path:
# output_location = 'output'
#
# Absolute path somewhere outside the CWD
# (NOTE Double \ required for special character escape. If location is on another computer
# or share drive, additional formatting steps may be required.
# See: https://stackoverflow.com/questions/7169845/using-python-how-can-i-access-a-shared-folder-on-windows-network for details )
#
# output_location = 'C:\\Users\\Username\\Documents\\my output folder'
#


output_location = 'output'

##################################
# File prefixes
# Change the text between the quotes if you want to adjust the default filenames
# Example:
# gephx_filename = 'my new filename'
# To change the timestamp format, see line 17 in member_subnetwork_functions
#################################

# the gephx file
gephx_filename = 'Total membership graph '

# excel file with summary details
summary_xls_filename = 'Member subnetworks '

# csvs with member_nbr/ individual_id and the subgraph they belong to
member_group_csv_filename = 'individual group '
individual_group_csv_filename = 'member group '
